services:
  - type: web
    name: construir-casitas-backend
    env: php
    plan: free
    buildCommand: "composer install && php artisan key:generate && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:TuClaveGenerada
      - key: DB_CONNECTION
        value: sqlite
